### ISSUE TITLE
PgSql driver - delimite() doesn't work correctly with FQN

### ISSUE THREAD

**Issue by mzstic** [nette/database#108]
We encountered problem, during upgrade to newest version.
INSERTs suddenly stopped working., after some digging, we found following:
1) INSERTs on their own work correctly
2) problem is when trying to get lastInsertId()
Nette\Database\Selection::764
```php
$primaryKey = $this->context->getInsertId(
    !empty($primarySequenceName)
        ? $this->context->getConnection()->getSupplementalDriver()->delimite($primarySequenceName)
        : $primarySequenceName
);
```
3) This throws following error: ```SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "web.product_id_seq" does not exist```
4) When I modified delimite function to work same way as delimiteFQN function in PgSqlDriver, all problems disappeared.

*Solution*
In identifier names should'nt be any `.` characters. Move `delimiteFQN` logic into `delimite` function.
When asking for delimition of not FQN identifier, it won't cause any problem.

**Comment by dg** [comment]
@mzstic can you check it?

**Comment by mzstic** [comment]
Seems to be working.
