### ISSUE TITLE
Multiple conditions by subselects are skipped

### ISSUE THREAD

**Issue by norbe** [nette/database#109]
If I call multiple times 
```
$context->table('product')
      ->where('product.id', $selection1)
      ->where('product.id', $selection2);
```
only first condition is used and second is skipped.

Its caused by [this line of SqlBuilder](https://github.com/nette/database/blob/master/src/Database/Table/SqlBuilder.php#L216), as json_encode convers selection to '{}' string.

**Comment by dg** [comment]
Can you fix it?

**Comment by norbe** [comment]
Yes, but I'm not sure how. Should I use [JsonSerializable](http://php.net/manual/en/class.jsonserializable.php) in Selection (supported by PHP >= 5.4.0) and convert the selection to query string?

**Comment by Unlink** [comment]
Maybee somehow use https://github.com/nette/database/blob/master/src/Database/Table/Selection.php#L633

Related to #14
