### ISSUE TITLE
Undefined offset while retrieving data from cache

### ISSUE THREAD

**Issue by temistokles** [nette/database#115]
In production environment with dozens of simultaneous requests, retrieving data from cache sometimes fails (this is true for newest version of Nette Database as well as older ones).

A long time ago a thread started at: https://forum.nette.org/cs/13466-undefined-offset-pri-dotazu-z-databaze-po-vymazani-cache

The issue is not consistent, sometimes the notice appears sometimes it does not (I was unable to test the conditions when this fails - they still seem magical to me). Moreover this is not the issue only when using count(), but any query.

The best approximation to errorneus conditions I could achieve is:
1) You need to access quite large database
2) Multiple accesses to the same table over the same data set with different queries is a plus stronly supporting the error appearing
3) You need to have cache enabled
**4) You need to use the same ResultSet in different conditions, e.g. once to read couple of rows and other time to get count(); or use limit() multiple times to get rows; or probably any duplicate access to the same data**

I strongly feel, the 4) is the real approximation to the mistake. Although I was unable to locate it directly in the code, it seems you need to access the data multiple times and cache only stores one case. The other case should logically be there, therefore you get a notice.

**Comment by norbe** [comment]
Could you please upload stored exception from tracy? When the problem appear, is it persistent problem or it fails just from time to time on some request?

I had some problem year ago, from that time I have been using nette\database without cache (I have not soo brave to test it on our customers)...

**Comment by temistokles** [comment]
Unfortunatelly I worked-around the issue using _clone_ where this issues were occuring and have no such log anymore.

The Tracy log provided no interesting details - only the fact that the requested cache key was missing (everything else was always application specific - the stacktrace).
