### ISSUE TITLE
UPDATE ... LIMIT

### ISSUE THREAD

**Issue by nechutny** [nette/database#120]
Hello,

I'm working with Nette Databse on MySQL and I can't  set limit to update query which is in MySQL supported - http://dev.mysql.com/doc/refman/5.7/en/update.html

Nette\NotSupportedException - LIMIT clause is not supported in UPDATE query

Is there any reason why it's not supported, or I can prepare PR?

**Comment by dg** [comment]
Sure, send the PR.
