### ISSUE TITLE
ResultSet: normalize float (1.234E+02) returns string

### ISSUE THREAD

**Issue by CZechBoY** [nette/database#121]
Hi,
I have field marked as NUMBER, but the value of this field is in format eg 1.234E+02.

Problem is here: https://github.com/nette/database/blob/master/src/Database/ResultSet.php#L168

**Comment by dg** [comment]
Could you explain it more?

**Comment by CZechBoY** [comment]
It is not related to Nette original library, the bug is just in my fork.
