### ISSUE TITLE
PostgreSQL 9.4.6, nette/database fails to find other schemes

### ISSUE THREAD

**Issue by Salamek** [nette/database#129]
When i try to get table like $context->table('api.table') i get:
Table 'api.table' does not exist

Nette Database 2.3.8 uses : 

``` SQL
SELECT DISTINCT ON (c.relname)
 c.relname::varchar AS name,
 c.relkind = 'v' AS view,
 n.nspname::varchar || '.' || c.relname::varchar AS "fullName"
FROM
 pg_catalog.pg_class AS c
 JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE
 c.relkind IN ('r', 'v')
 AND n.nspname = ANY (pg_catalog.current_schemas(FALSE))
ORDER BY
 c.relname;
```

To find active schemes now, but it fails, i have 3 schemes `api`, `test`, `public`... this SQL finds only `public` : 

| name | view | fullName |
| --- | --- | --- |
| test | f | public.test |

problem is in `pg_catalog.current_schemas(FALSE)`, it returns only:

| current_schemas |
| --- |
| {public} |

But nette/database version  v2.3.4 works just fine  for me, v2.3.5 fails^ so there must be some change in v2.3.5 breaking this

**Comment by Salamek** [comment]
Is this project dead or what ? I cant use PgSQL databases cos this^ ....

I had to downgrade nette/database to v2.2.5 cos this bug and cos bug in v2.3.4 where primary keys are not found in PgSQL database... after this, i'm moving to Doctrine...

**Comment by dg** [comment]
Please send pull request with fix.

**Comment by Salamek** [comment]
@dg when i will get some free time i will try to create a PR

**Comment by milo** [comment]
@Salamek There has been changes in PostgreSQL reflection in 2.3.0. If you want to work with schemas, set them into the `search_path` on connection:
```sql
SET search_path TO public, api, test;
```
It is a workaround a little bit.

**Comment by milo** [comment]
IMHO, the reflection should return all user tables in FQN and non-FQN from current schemas only. E.g.
```sql
SELECT DISTINCT ON (c.relname)
	c.relname::varchar AS name,
	c.relkind = 'v' AS view
FROM
	pg_catalog.pg_class AS c
	JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE
	c.relkind IN ('r', 'v')
	AND n.nspname = ANY (pg_catalog.current_schemas(FALSE))
UNION ALL
SELECT
	n.nspname::varchar || '.' || c.relname::varchar AS name,
	c.relkind = 'v' AS view
FROM
	pg_catalog.pg_class AS c
	JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE
	c.relkind IN ('r', 'v')
	AND n.nspname NOT IN ('pg_catalog', 'information_schema')
```

With `serach_path TO public` it will result to:
```
authors
books
public.authors
public.books
some_other.table
```

**Comment by dg** [comment]
@Salamek what's the hitch?

**Comment by Salamek** [comment]
@dg sorry, i'm not using nette/database anywhere since ~2016 (and i probably never will), and i have no spare time to spend on this issue... and i bet it is fixed long time ago anyway :smile_cat: so i'm closing this issue, feel free to reopen if this bug is still in the code.
