### ISSUE TITLE
Connection is not lazy on default

### ISSUE THREAD

**Issue by petrjirasek** [nette/database#130]
Hi,

I have just found a contradiction between source code and documentation. If I understand this correctly, the documentation (here https://doc.nette.org/en/2.3/database) says that the connection is lazy on default but If I look here https://github.com/nette/database/blob/master/src/Database/Connection.php#L52 it seems that it is not true.

The paragraph in documentation:
> All connections are created as “lazy” by default. This means the connection is established when it's needed, not when you create a Connection instance. You can disable this behavior by passing 'lazy' => FALSE configuration.

What is desired behaviour? Is a mistake in the source code or in the documentation?

Thanks!

**Comment by dg** [comment]
It seems that documentation is wrong

**Comment by petrjirasek** [comment]
Ok, thanks. I have tried to propose a change of documentation. https://github.com/nette/web-content/pull/427

**Comment by Unlink** [comment]
@dg It should be closed?
