### ISSUE TITLE
Can not add multiple selections as condition on the same column

### ISSUE THREAD

**Issue by michal-kusy** [nette/database#14]
Example code:
```php
    $q = $db->table('users');
    foreach(array('admin','user') as $role) {
       $q->where('id',
                         $db->table('user_role')
                               ->select('user_id')
                               ->where('role_id',$role));
    }
```
Example code adds only first selection, because of hash check in SqlBuilder.php line 200. It's because Selection does not have any unique public property and so it's always translated as empty object {}  in JSON.

**Comment by norbe** [comment]
This issue should be fixed..
