### ISSUE TITLE
MySqlDriver: Is formatLike handling properly backslash?

### ISSUE THREAD

**Issue by CZechBoY** [nette/database#147]
Hi,
I think that Nette\Database\Drivers\MySqlDriver::formatLike method is not handling backslash properly.
If I test it on value `abc\.abc` then the result should be `abc\\\\.abc` (4x backslash) and now it returns `abc\\\\\\\\.abc` (8x backslash).

Is anybody else experiencing this?

Thanks.

ps. The fix should be remove backslash from addclashes's charlist parameter.

**Comment by dg** [comment]
Reverted - it seems to me that formatLike() works correctly.
