### ISSUE TITLE
Change minimal supported PHP verson to 7.1 for 3.0

### ISSUE THREAD

**Issue by foxycode** [nette/database#158]
- bug report? no
- feature request? yes
- version: 3.0

I'd like to see scalar typehints in 3.0. But it's not fully possible before PHP 7.1 because of missing nullable type. What do you think about supporting 7.1 as minimal version? And I don't mean just for this package, but for all Nette packages.

**Comment by dg** [comment]
For all packages no, only for packages, where it really makes sense. We will see.

**Comment by dg** [comment]
Done
