### ISSUE TITLE
Usage example from README is outdated

### ISSUE THREAD

**Issue by plashenkov** [nette/database#174]
I'm faced with the same issue: https://github.com/nette/database/issues/167

The point is that this example: https://github.com/nette/database#queries from main README is not working. We cannot instantiate \Nette\Database\Context in such way anymore. We must pass the second argument, but how, what we should do to _properly_ create an instance of IStructure to pass as the second argument — we have no example.

I'd like to use nette/database outside of Nette Framework, as a standalone component, but the example from README is not working for the actual version of nette/database.

**Comment by dg** [comment]
More current is https://doc.nette.org/en/2.4/database, I'll fix readme.md

**Comment by plashenkov** [comment]
https://github.com/nette/database#connection

Still wrong code in README:
```php
$database = new Nette\Database\Context($connection);
```

**Comment by dg** [comment]
Oh…

**Comment by plashenkov** [comment]
It's fine now, thank you very much!

The only thing that below: https://github.com/nette/database#nette-database-table already Context is used. What it is and how to create it — that is not described. It would be very nice to have at least the most concise description of what a Context is and how it differs from a Connection. From the source code, it has almost the same methods as the Connection. Is it enough to use only Connection in most cases or is it better to instantiate and use the Context?

With this information README will be self-sufficient.
