### ISSUE TITLE
Bug in Tracy Bar - ConnectionPanel

### ISSUE THREAD

**Issue by Lumeriol** [nette/database#176]
- bug report? yes
- feature request? no
- version: latest, commit 3e71317

### Description
Bug in file ConnectionPanel.panel.phtml caused by strict_type.
Only show in Tracy bar if Debugger option is on in config.local.neon.

**Error:** Nette\Bridges\DatabaseTracy\ConnectionPanel
**TypeError:** htmlspecialchars() expects parameter 1 to be string, integer given in vendor\nette\database\src\Bridges\DatabaseTracy\templates\ConnectionPanel.panel.phtml:46

**Stack trace:**
#-0 vendor\nette\database\src\Bridges\DatabaseTracy\templates\ConnectionPanel.panel.phtml(46): htmlspecialchars(1, 0, 'UTF-8')
#-1 vendor\nette\database\src\Bridges\DatabaseTracy\ConnectionPanel.php(139): require('C:\\localhost\\We...')
#-2 vendor\tracy\tracy\src\Tracy\Bar.php(153): Nette\Bridges\DatabaseTracy\ConnectionPanel->getPanel()
#-3 vendor\tracy\tracy\src\Tracy\Bar.php(108): Tracy\Bar->renderPanels()
#-4 vendor\tracy\tracy\src\Tracy\Debugger.php(266): Tracy\Bar->render()
#-5 [internal function]: Tracy\Debugger::shutdownHandler()
#-6 {main}

**Comment by dg** [comment]
fixed
