### ISSUE TITLE
Error while binding short string with slash suffix

### ISSUE THREAD

**Issue by forrest79** [nette/database#177]
- bug report? yes
- feature request? nono
- version: 2.4.3

### Description
Get error syntax exception, when mixing short (with suffix \) and long string parameters binding to INSERT or UPDATE query (maybe there are probably more scenarios to get this error).

### Steps To Reproduce
I have tested this with PostqreSQL. Let's create this simple table:

```sql
CREATE TABLE test
(
  col1 text,
  col2 text,
  col3 text
);
```

Then run this command:

```php
/** @var \Nette\Database\Context $context */
$context->table('test')->insert([
	'col1' => 'some text \\', // shorter than 20
	'col2' => 'some text longer than 20 characters',
	'col3' => 'some text', // shorter than 20
]);
```
This exception is thrown:

```
Nette\Database\DriverException #42601

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 1: ... ("col1", "col2", "col3") VALUES ('some text \', ?, 'some te...
```

This behavior is probably fixed in 3.0.0-alpha with commit https://github.com/nette/database/commit/644b587fc548a83899325bdb22b3ee299fe9995f. To fix this in 2.4 branch it is possible to change SqlPreprocessor->formatValue to bind all strings as variable, not only strings longer than 20 characters. Bud I don't why this logic is there, maybe this update could be BC?

**Comment by dg** [comment]
According to the PostqreSQL documentation, everything is ok: https://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS

> A string constant in SQL is an arbitrary sequence of characters bounded by single quotes ('), for example 'This is a string'. To include a single-quote character within a string constant, write two adjacent single quotes, e.g. 'Dianne''s horse'. Note that this is not the same as a double-quote character (").

There is a mention switch `standard_conforming_strings`. Can you find out what value it has? If it is `true`, it looks like a serious security issue in PDO.

**Comment by milo** [comment]
This is some bug in PDO parameters binding. The `$pdo->quote()` respects `standard_conforming_strings` setting.
```
# SET standard_conforming_strings TO on
$pdo->quote('BACK \\ SLASH')  =  BACK \ SLASH

# SET standard_conforming_strings TO off
$pdo->quote('BACK \\ SLASH')  =  BACK \\ SLASH
```

Query `INSERT INTO test ("col1", "col2", "col3") VALUES ('some text \', 'abc', 'def')` is valid PostgreSQL query with `standard_conforming_strings` set to `on` (which means, "Handle backslash as ordinary character").

IMHO the bug is in internal PDO values binding code when they are looking for `?` in prepared query. The `?` is not found, parameter is not binded correctly and PDO executes SQL which contains `?`. The whole exception message is:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 1: INSERT INTO test (col1, col2, col3) VALUES ('\', ?, 'x')
                                                          ^ in D:\Web\temp\pdo\test2.php:14
```
Focus on the `^` and where it points.

Code to reproduce:
```php
$pdo = new PDO('pgsql:host=localhost;dbname=test', 'test', 'test');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$pdo->query('SET standard_conforming_strings TO on');

$stmt = $pdo->prepare("INSERT INTO test (col1, col2, col3) VALUES ('\\', ?, '')");
$stmt->bindValue(1, 'x', PDO::PARAM_STR);
$stmt->execute();
```

If you don't, I'll report PHP bug in the evening.

**Comment by milo** [comment]
Workaround is `SET standard_conforming_strings TO off` if an application does not depends on it.
In that case, PDO internals code works.

**Comment by dg** [comment]
That would be great if you could report it, I do not know the PostgreSQL at all.  (I only develop its drivers :-) )

**Comment by dg** [comment]
Can `?` be replaced directly by the database instead of the PDO?

**Comment by dg** [comment]
Workaround 041e3529b436b4670d8004838b2ee8f1ddbf438d

**Comment by dg** [comment]
We have solved it by workaround because sending all strings as parameters causes incompatibility in PostgreSQL:

`SELECT 'string'` vs `SELECT ?` + parameter `'string'` leads to `SQLSTATE[42P18]: Indeterminate datatype: 7 ERROR:  could not determine data type of parameter $1`.

**Comment by milo** [comment]
> Can `?` be replaced directly by the database instead of the PDO?

There is a [PREPARE statement](https://www.postgresql.org/docs/9.6/static/sql-prepare.html), but I don't know syntax using `?`.

> sending all strings as parameters causes incompatibility

It is probably related to [PHP #36652](https://bugs.php.net/bug.php?id=36652), workaround is mentioned in comment.

**Comment by dg** [comment]
IMHO just PDO::ATTR_EMULATE_PREPARES causes this issue…

**Comment by milo** [comment]
I don't think so. With ATTR_EMULATE_PREPARES it uses PostgreSQL `PREPARE` statement. It translates `?` into `$1`.
```php
$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, true);
# PG log
# LOG:  statement: INSERT INTO test (col1, col2, col3) VALUES ('a', 'x', ' ')

$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
# PG log
# LOG:  execute pdo_stmt_00000001: INSERT INTO test (col1, col2, col3) VALUES ('a', $1, ' ')
# DETAIL:  parameters: $1 = 'x'
```

But with buggy query from this issue, it fails in the same way in both cases:
```
STATEMENT:  INSERT INTO test (col1, col2, col3) VALUES ('\', ?, ' ')
```

**Comment by milo** [comment]
It seems to me that issue appears only when some string ends with `\\`.
```php
$stmt = $pdo->prepare("INSERT INTO test (col1, col2, col3) VALUES ('\\', ?, ' ')");  # BUGGY
$stmt = $pdo->prepare("INSERT INTO test (col1, col2, col3) VALUES ('\\ ', ?, ' ')"); # OK
$stmt = $pdo->prepare("INSERT INTO test (col1, col2) VALUES ('\\', ?)"); # OK
```

**Comment by dg** [comment]
What about `$stmt = $pdo->prepare("INSERT INTO test (col1, col2, col3) VALUES ('\\''  ', ?, ' ')");`, ie doesn't end with, but contains \\ before '

**Comment by milo** [comment]
It's buggy too.

**Comment by milo** [comment]
Reported [PHP #74996](https://bugs.php.net/bug.php?id=74996).

**Comment by forrest79** [comment]
Hi, big thanks for really quick fix!
