### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Lumeriol** [nette/database#180]
- bug report? yes

- version: latest, commit 32fd704

### Description
Bug in file nette\database\src\Database\Table\ActiveRow.php:19.

Declaration of Nette\Database\Table\ActiveRow::ref(string $key, ?string $throughColumn = NULL): ?Nette\Database\Table\ActiveRow must be compatible with Nette\Database\Table\IRow::ref(string $key, ?string $throughColumn = NULL): ?Nette\Database\Table\IRow

After update, website stop working with this compile error. Nothing else was changed in my code, so it seems that there is problem in ActiveRow.

Tested on dev-master Sandbox with PHP 7.2b2.

**Comment by dg** [comment]
fixed
