### ISSUE TITLE
joinWhere with multiple joins throws InvalidArgumentException

### ISSUE THREAD

**Issue by syky01** [nette/database#181]
- bug report? yes
- feature request? no
- version: 2.4.2 

### 
There is problem with throwing InvalidArgumentException (There are more placeholders than passed parameters.) when you use multiple joinWhere() functions. If you switch JoinWhere in example, it works. I Think there is problem in parseJoinConditions() function in SqlBuilder class.

If you look what $tableJoins variable contain its 
[
 [b1] = ['some data'] 
 [author] = []
 [b2] = ['some data']  
]

### Steps To Reproduce
 $this->database->table('author')
->select('*')
->alias(':book', 'b1')
->alias(':book', 'b2')
->joinWhere('b1', ':b1.author_id = author.id')
->joinWhere('b2', ':b2.author_id = author.id AND b2.title LIKE ?', '%e%')-fetch();

**Comment by dg** [comment]
Closed by #182
