### ISSUE TITLE
Receiving "Found duplicate columns in database" with inner select (MySQL)

### ISSUE THREAD

**Issue by Shaked** [nette/database#184]
- bug report? yes
- feature request? no
- version: v2.4.2

### Description
Hey, I am using MySQL. When I am trying to use an inner select with a similar column name, I end up seeing the following message:
> Found duplicate columns in database result set: 'userId' (from u, up).

#### Setup Database
```
CREATE TABLE IF NOT EXISTS `u` (
   userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO u (username) VALUES ('user123'); 

CREATE TABLE IF NOT EXISTS `up` (
   pid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   userId INT NOT NULL, 
   INDEX(userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

#### Execute
```
$params = ['username' => 'user123'];
$sql = 'SELECT up.pid,up.userId FROM up WHERE up.userId=(SELECT u.userId FROM u WHERE username=?)';
$ret = $db->query($sql, ...$params)->fetchAll();
```

**Comment by dg** [comment]
I think you have a bug in the code. It is not possible to use `...$params` where there are keys. 

Use simply `$params` without `...`

**Comment by Shaked** [comment]
@dg yes, that's correct, sorry for that.
 
I think I copied something badly because I haven't gotten an error about the unpacking. Will try to reproduce, but in the meanwhile, I am closing this issue.
