### ISSUE TITLE
Selection->page bug

### ISSUE THREAD

**Issue by 2bad2furious** [nette/database#191]
- bug report? yes
- feature request? no

### Description
Paging doesn't take into account GROUP.

### Example

```
$selection = $database->table('table1')
->group('column');
```

$selection->page sets the $numOfPages to `$selection->count('')`, which is just 
`SELECT count(*) FROM table1`,
where it should be 
```
SELECT count(*)
 FROM table1 
GROUP BY column
```

**Comment by dg** [comment]
I don't understand.

**Comment by 2bad2furious** [comment]
Should be understandable now :)
