### ISSUE TITLE
Excessive number of queries for metadata by PDO

### ISSUE THREAD

**Issue by repli2dev** [nette/database#212]
Version: 2.4.6

When analysing queries from the DB side (PostgreSQL) we have discovered that the PDO is making a excessive number of queries for `pgclass` and `pgtype`... We investigated that these queries origin from PDO extension itself (hence not visible in any query monitoring done on PHP runtime) and are caused by nette/database from `Helpers::detectTypes()` where `PDO::getColumnMeta()` is called.

The excessiveness is that we have around 500 queries on page and this generates around 1500 additional queries (depends on number of columns and custom types), which are quite fast, but still takes around 5% of whole request.

Could the method `detectTypes()` be efficient? Maybe caching? (However that may not be a good idea as schema can change during execution.)

**Comment by dg** [comment]
Are these queries similar?

**Comment by repli2dev** [comment]
@dg  yes, only OID changes and in high numbers they are event duplicate... See pgsql_stmt_get_column_meta in https://www.askapache.com/pub/php/ext/pdo_pgsql/pgsql_statement.c

**Comment by repli2dev** [comment]
This solves our issue only partially (for the exact duplicate queries) thanks for that!  ... Though I am not able to came up with any better solution as the the queries with different param values cannot be cached... The same for different queries referencing same table columns (i.e. both referencing `foo.my_column`) due to the fact that DBAL doesn't really know they are the same columns and asks for `0..n` column`s metadata.
