### ISSUE TITLE
Undefined variable: connection

### ISSUE THREAD

**Issue by Lumeriol** [nette/database#246]
Version: 3.0-dev
Commit: c3b03b764307e4969d5446198de74d3849f6ada5

### Bug Description
ErrorException: Undefined variable: connection in \vendor\nette\database\src\Bridges\DatabaseTracy\templates\ConnectionPanel.panel.phtml:20

### Possible Solution
As quick fix add parameter $connection on line 137 in ConnectionPanel.php -> 
return Tracy\Helpers::capture(function () use ($queries) {

**Comment by dg** [comment]
Fixed
