### ISSUE TITLE
jetbrains/phpstorm-attributes dev-master vs 1.0

### ISSUE THREAD

**Issue by lukaspijak** [nette/database#302]
Version: v3.1.8

### Bug Description
Hi, if you have installed `jetbrains/phpstorm-attributes` in version 1.0, you can not install `nette/database v3.1.8`

### Steps To Reproduce
![image](https://github.com/nette/database/assets/2571714/cad2eab8-9fa0-44b3-8492-1a26fb3911a6)

### Possible Solution
You can add to `composer.json`:

```json
"jetbrains/phpstorm-attributes": "*",
```

**Comment by spaze** [comment]
Hi, similar problem when my `composer.json` doesn't specify `minimum-stability` (and `stable` is then used as the default):

> \- nette/database v3.1.8 requires jetbrains/phpstorm-attributes dev-master -> found jetbrains/phpstorm-attributes[dev-master] but it does not match your minimum-stability.

**Comment by JanTvrdik** [comment]
`jetbrains/phpstorm-attributes` should be a dev-dependency, it's not needed at runtime.

**Comment by dg** [comment]
@JanTvrdik won't PhpStan then report errors?

**Comment by JanTvrdik** [comment]
It should work just fine. Having dev-only attributes is valid pattern. For example `#[Sealed]` attribute from https://github.com/jiripudil/phpstan-sealed-classes is also suggested to be installed as dev-dependency.

**Comment by dg** [comment]
fixed
