### ISSUE TITLE
sqlite: parseColumnType gives a warning

### ISSUE THREAD

**Issue by marcelklinek** [nette/database#315]
Version: 3.2.5

### Bug Description
When I upgrade to 3.2.5 from 3.2.0 database layer starts throwing exceptions. I am using sqlite db with Database explorer.

First it gives a warning in parseColumnType:

Warning
Undefined array key 1

Then if skipped, throws a TypeError:

TypeError
strtoupper(): Argument # 1 ($string) must be of type string, null given

I attach a stack trace and table description.

### Steps To Reproduce
A select/insert into sqlite both produce this error. 

[call_stack.txt](https://github.com/user-attachments/files/18228766/call_stack.txt)

<img width="775" alt="table_struct" src="https://github.com/user-attachments/assets/b0a4cad2-9775-4a27-b74d-44b1a90ca214" />

### Offering to help

I can try to prepare a PR if you point me in the right direction (very new to nette)

**Comment by dg** [comment]
Can you dump what `$row` contains?

**Comment by marcelklinek** [comment]
My bad, this is not a bug.

One of my tables (a different one) was missing a type on a column, which I discovered with `dump($row);`:

```
Nette\Database\Row
cid: 1
name: 'paid'
type: 'INTEGER'
notnull: 1
dflt_value: null
pk: 0

Nette\Database\Row
cid: 2
name: 'lead'
type: ''
notnull: 1
dflt_value: null
pk: 0
```

When I add the type, all works fine, sorry for false alarm.

Thanks for the pointer and for your work, David!
