### ISSUE TITLE
Allow specifying ON clause filtering condition.

### ISSUE THREAD

**Issue by hrach** [nette/database#35]
Would be very useful to allow specify conidtion, which would be add to ON clause. The question is the syntax. The main usecase are condition with OR. Other usecases are against NDB principle to select only from one table at once.

**Usecase:**
 Select all photos, which "current user" is author or has allowed acces in `access` table.

```sql
SELECT photos.*
FROM photos
    LEFT JOIN access ON (photo.id = access.photoId AND access.userId = ?)
WHERE
    photo.authorId = ?
OR acess.userId IS NOT  NULL
```
**Need api suggestions:**

```php
$books = $context->table('photos');
$books->whereSoft('access.userId = ?', $userId);
$books->where('photo.authorId = ? OR access.userId IS NOT NULL');
```

Things to discuss:
- whereSoft method name
- support for OR in where SOFT?
- some bigger overhaul for SqlBuilder (alias supporting, etc?)

cc @milo @norbe @dg nette/nette#1436

---------

Edit: it is possible to rewrite it without the condition included in join, but then is needed some either grouping by or distinct, which would give much worse EXPLAIN, some temporary table needed for mysql.

**Comment by MartinMystikJonas** [comment]
+1

We need this right now in our project. We did workaround using sub-select but it is not nice.

**Comment by michallohnisky** [comment]
+1

**Comment by helvete** [comment]
:+1:

**Comment by norbe** [comment]
I have prepared support for ON conditions (and alias support is already merged). I would be glad for comments..

**Comment by norbe** [comment]
@MartinMystikJonas @michallohnisky @helvete No one?

**Comment by MartinMystikJonas** [comment]
@norbe I have nothing to comment. I like that.

**Comment by helvete** [comment]
I Iike it.

**Comment by Unlink** [comment]
@dg please close #125
