### ISSUE TITLE
undefined method validateConfig

### ISSUE THREAD

**Issue by Keeehi** [nette/database#51]
V souboru src/Bridges/DatabaseDI/DatabaseExtension.php na řádku 56 se volá metoda validateConfig, která neexistuje. Nebo alespoň já dostávám tuto výjimku
```
Nette\MemberAccessException
Call to undefined method Nette\Bridges\DatabaseDI\DatabaseExtension::validateConfig().
```
Stane se to když v config.local.neon odstraním sekci nette: a podsekci database: co byla předtím uvnitř přesunu na její úroveň. Což tedy je pravděpodobně špatně, ovšem i přesto by nette nemělo volat neexistující metodu, nebo pokud jsem to rozbil tou konfigurací, tak by mělo předložit hezčí výjimku, která by říkala co jsem rozbil a jak to opravit.

**Comment by JanTvrdik** [comment]
You have probably outdated `nette/di` dependency, try running `composer update`. The method [was added](https://github.com/nette/di/commit/32caa728d2fd7de245d66dcc782956815da83de0) 21 days ago to `CompilerExtension`.

**Comment by Keeehi** [comment]
It was new installation, but I had mismatch in versions in composer. Sorry about that.
