### ISSUE TITLE
toArray() on deleted ActiveRow creates infinite loophole

### ISSUE THREAD

**Issue by ghost** [nette/database#60]
I have noticed some buggy behavior when I was attempting to delete row from database, but also preserve the ActiveRow with data, for logging purpose. While this operation is incorrect, some exception would be more suited then current behavior.

**First case** - produces infinite loophole.

	function delete( ActiveRow $note )
	{	
		$note->getTable()->createSelectionInstance()
			->wherePrimary( $note->id )
			->delete();
				
		dump( $note->toArray() ); // <-- isded
	}

**Second case** - produces undefined offset notice.

	function delete( ActiveRow $note )
	{
		$note->delete();
		
		dump( $note->toArray() ); // <-- isded
	}

**Versions**
Nette: 2.3.0
Nette/Database: 2.3.0
PHP: 5.5.9

**Comment by dg** [comment]
Can you fix it?

**Comment by kucbel** [comment]
No, but I will add a follow-up on how exactly to reproduce the issue. When selecting a row, do not specify any columns, after fetching it, re-run the script for the column cache to kick in. Then, delete the row and try calling toArray().
