### ISSUE TITLE
PHP fall when accessing invalid table with own conventions class

### ISSUE THREAD

**Issue by foxycode** [nette/database#62]
I made simple demonstration on latest sandbox here: https://github.com/foxycode/sandbox-502-error-test/commit/e3cf48c24e3a5364ed95e0f11f163d5e1a329138

I tried it on 2 different servers. One with nginx and php-fpm 5.5.23, second with Apache and mod-php 5.5.9.

**Comment by matej21** [comment]
It creates infinite recursion. Try to debug it with xdebug and you'll see

**Comment by foxycode** [comment]
Never used that.

**Comment by foxycode** [comment]
Fixed by https://github.com/nette/database/commit/e717a69d6af4499ce69768067163e80cb7b37228

Many thanks @matej21 

@dg I hope for next release soon.
