### ISSUE TITLE
Wrong join generating

### ISSUE THREAD

**Issue by nechutny** [nette/database#72]
Hello,
I have these primitive tables:

DROP TABLE IF EXISTS `firstTable`;
	CREATE TABLE `firstTable` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `firstFk` int(11) NOT NULL,
	  PRIMARY KEY (`id`),
	  KEY `firstFk` (`firstFk`),
	  CONSTRAINT `firstTable_ibfk_1` FOREIGN KEY (`firstFk`) REFERENCES `secondTable` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=latin1;

	DROP TABLE IF EXISTS `secondTable`;
	CREATE TABLE `secondTable` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  PRIMARY KEY (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=latin1;

and trying to do following: 

$result = $this->db->table("firstTable")->select("firstTable.id, secondTable.id");
dump($result->getSql());

Result is exception No reference found for $firstTable->secondTable. I've found, that it works only if I name column with FK with the same name as target table (used stripos in DiscoveredConventions). I think that it is not correct behavior because we can also use foreign keys. When I dumped variables in getBelongsToReference method, then I've found that for correct join should be line if (stripos($column, $key) !== FALSE) { changed to if (stripos($targetTable, $key) !== FALSE) {, because $tableColumns contains eg. firstFk => "secondTable".

I'm not sure if this is real bug, or just my mistake and if is potencial solution ok. I've created for this example sandbox - http://pastebin.com/bm1HHCut

**Comment by matej21** [comment]
That is a correct behaviour. Nette derives "joining key" from the column name, not from the target table name. See the doc: http://doc.nette.org/en/2.3/database-selection#toc-joining-key

You need to write this:
```php
->select('firstFk.id')
```
(`first.id` or any other substring should work as well)

**Comment by Unlink** [comment]
@dg you should close this
