### ISSUE TITLE
SqlsrvDriver poorly composed TOP n if used SELECT DISTINCT

### ISSUE THREAD

**Issue by JosefDohnal** [nette/database#75]
SELECT - SQL Command - SELECT Clause
```SQL
SELECT [ALL | DISTINCT] [TOP nExpr [PERCENT]] Select_List_Item [, ...] ...
```

If used $dbsel->select("DISTINCT column")  SQL is "SELECT **TOP** 10 DISTINCT" column but must be "SELECT DISTINCT **TOP 10** column".

In the file database/src/Database/Drivers/SqlsrvDriver.php on line 92:
```php
$sql = preg_replace('#^\s*(SELECT|UPDATE|DELETE)#i', '$0 TOP ' . (int) $limit, $sql, 1, $count);
```
change regular expression:
```php
'#^\s*(SELECT|UPDATE|DELETE)#i'
```
to
```php
'#^\s*(SELECT\s*DISTINCT|SELECT\s*ALL|SELECT|UPDATE|DELETE)#i'
```

**Comment by dg** [comment]
Fixed by b3b6e9bb73702119a596b4f408bad4356fc53cb1
