### ISSUE TITLE
Table '$name' does not exist.

### ISSUE THREAD

**Issue by semerak-michal** [nette/database#88]
Zdravím,

myslím, že úpravy v issue #79 omylem způsobily, že se vyhazuje výjimka tam kde dřív ne.

Metoda `resolveFQTableName` v `Nette\Database\Strucure` se volá z metody `getPrimaryKey` téže třídy. Problém nastane ve chvíli, když je argumentem pohled.

Pohledy se v metodě loadStructure přeskakují:

```php
foreach ($structure['tables'] as $tablePair) {
    if ($tablePair['view']) {
        continue;
    }
    ....
```

a díky tomu v `$this->structure['columns']` ani `$this->structure['primary']` nikdy nebude a vyskočí ona vyjímka.

**Comment by Unlink** [comment]
Hi, please use english next time.
I don't know why it skips view analyse. Introduced here 5f92e8cf8d5480ed3e4172ef5d93ef698bbb0b7b
I think that it should analyse views to. Of course PK and relations analyze is not needed, but analyse columns should be fine.
I prepared #93

**Comment by janfiedler** [comment]
I have same problem, when data are read from View after update to 2.3.5 from 2.3.4.

**Comment by dg** [comment]
Closed by #93
