### ISSUE TITLE
Extending ActiveRow

### ISSUE THREAD

**Issue by tino415** [nette/database#90]
Sometimes i need functions based on row data, for example if i have `$user->first_name` and `$user->last_name`, and i want to have function `$user->full_name` that just concat these two attributes.

I imagine something like extend ActiveRecord, then create factory and inject that factory into Nette\Database\Table\Selection. What do you think ?

**Comment by JanTvrdik** [comment]
This has been proposed and rejected many times.

**Comment by tino415** [comment]
So what is common practice to solve such situations ?

**Comment by tino415** [comment]
I describe mi situation, I have 3 level hierarchycal data in one table, level is stored in column level, I vould like to access them lik `$level1->level2->level3` but instead i can only do `$item->item->item`, is there common practice how to achieve this, (sri for reopening, but I think it is better probabilty to get enswer :D)

**Comment by nechutny** [comment]
What about using YetORM? It's basic ORM layer allowing this. You will get entity which can be extended by methods like you suggested. Easy to learn, understand and extend.

**Comment by tino415** [comment]
I'm doing just small part of bigger project, so I need to achieve this with sandbox.
